spring:
  application:
    name: ms-courses
  datasource:
    url: jdbc:postgresql://localhost:5432/ms-courses
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect

server:
  port: 8802
