spring:
  application:
    name: ms-users
  datasource:
    url: jdbc:mysql://localhost:3306/ms-users
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8801
